export enum UserProviderConstants {
  USER_REPOSITORY = 'USER_REPOSITORY',
  USER_REPOSITORY_SAVER = 'USER_REPOSITORY',
  USER_REPOSITORY_FINDER = 'USER_REPOSITORY',
  USER_REPOSITORY_REMOVER = 'USER_REPOSITORY_REMOVER',
}
