export enum RepositoryProviders {
  USER_REPOSITORY = 'USER_REPOSITORY',
  LANGUAGE_REPOSITORY = 'LANGUAGE_REPOSITORY',
  NATIVE_LANGUAGE_REPOSITORY = 'NATIVE_LANGUAGE_REPOSITORY',
  LEARNING_LANGUAGE_REPOSITORY = 'LEARNING_LANGUAGE_REPOSITORY',
}
